---
#- name: Update and upgrade apt packages
#  become: true
#    apt:
#      upgrade: yes
#      update_cache: yes
#      cache_valid_time: 86400 #One day

- name: Install aptitude using apt
  become: true
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install required system packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items::
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools

