
#- name: Create k8s cluster - prerequisites
#  hosts: all, !testers
#  gather_facts: false
#  roles:
#    - prerequisites
- name: debug565656565
  debug: var=kubeadm_token

- name: Create k8s cluster - master init
  hosts: masters
  gather_facts: false
  roles:
    - master

- name: Create k8s cluster - worker join
  hosts: workers
  gather_facts: false
  roles:
    - worker