---

- name: Create k8s cluster - prerequisites
  hosts: all, !testers
  gather_facts: false
  roles:
    - prerequisites

- name: Create k8s cluster - master init
  hosts: masters
  gather_facts: true
  roles:
    - master
    - verify

- name: Create k8s cluster - worker join
  hosts: workers
  gather_facts: true
  roles:
    - worker

- name: Wait for 30 sec
  hosts: all, !testers
  wait_for:
    timeout: 30 # seconds

- name: Create k8s cluster - verification
  hosts: masters
  gather_facts: false
  roles:
    - verify

#- hosts: masters
#  tasks:
#    - name: all nodes
#      shell: kubectl get nodes
#      register: node_list
#
#    - name: print
#      debug: var=node_list
