---

- name: Create k8s cluster - prerequisites
  hosts: all, !testers
  gather_facts: false
  roles:
    - prerequisites

- name: Create k8s cluster - master init
  hosts: masters
  gather_facts: true
  roles:
    - master

- name: Create k8s cluster - worker join
  hosts: workers
  gather_facts: true
  roles:
    - worker

- hosts: masters
  tasks:
    - name: all pods
      k8s_facts:
        kind: Pod
      register: pod_list
      
    - name: print
      debug: var=pod_list
