---

- name: Create k8s cluster - prerequisites
  hosts: all, !testers
  gather_facts: false
  roles:
    - prerequisites

- name: Create k8s cluster - master init
  hosts: masters
  gather_facts: true
  roles:
    - master

- name: Create k8s cluster - worker join
  hosts: workers
  gather_facts: true
  roles:
    - worker

#- hosts: tester1
#  tasks:
#    - name: hostname
#      command: hostname
#      #shell: ls -la
#      register: hh
#
#    - debug: var=hh
#      -

- hosts: masters
  become: true
  tasks:
    - name: Get All Pods
      k8s_info:
        kind: Pod
      register: pod_list

    - name: Print out all pods
      debug: var=pod_list