---

- name: Create k8s cluster - prerequisites
  hosts: all, !testers
  gather_facts: false
  roles:
    - prerequisites

- name: Create k8s cluster - master init
  hosts: masters
  gather_facts: true
  roles:
    - master
    - verify

- name: Create k8s cluster - worker join
  hosts: workers
  gather_facts: true
  roles:
    - worker

- name: Create k8s cluster - verification
  hosts: masters
  gather_facts: false
  pre_tasks:
    - name: Wait for 30 sec...
      wait_for:
        host: '{{ ansible_host }}'
        delay: 30
  roles:
    - verify
