- name: Create k8s cluster - prerequisites
  hosts: all, !testers
  gather_facts: false
  roles:
    - prerequisites

- name: Create k8s cluster - master init and worker join
  hosts: all, !testers
  gather_facts: false
  roles:
    - creation