---
# tasks file for worker

- name: test
  debug:
    msg: 'this is a test'

- name: test2
  debug:
    #msg: "the token: {{ kubeadm_token }}"
    msg: "the token: {{ hostvars[masters]['kubeadm_token'] }}"