---
# tasks file for creation
- name: Reset Kubernetes component in master
  become: true
  shell: "kubeadm reset --force"
  register: reset_cluster_master
  # TODO: check what happens

- name: Print reset master
  debug: var=reset_cluster_master

- name: Get master node IP address
  set_fact:
    master_ip: "{{ hostvars[groups['masters'][0]].ansible_host}}"

- name: Print out master IP address
  debug: var=master_ip

- name: Print out master name
  debug: var="{{ inventory_hostname }}"

- name: Generate kube token in master
  command: kubeadm token generate
  register: kube_token_output
  run_once: true

- name: Save kube token in master
  set_fact:
    kubeadm_token: "{{ kube_token_output.stdout }}"

- name: Print out kube_token in master
  debug: var=kubeadm_token

## kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.244.132
#- name: Init Kubernetes cluster - master node
#  #when: reset_cluster_master is succeeded
#  become: true
#  shell: |
#    kubeadm init --pod-network-cidr 10.244.0.0/16 \
#                 --token {{ kubeadm_token }} \
#                 --apiserver-advertise-address {{ master_ip }} \
#                 --node-name k8s-master
#  register: init_cluster_master
#
#- name: Print init master
#  debug: var=init_cluster_master
