---
# tasks file for creation
- name: Get master node IP address
  set_fact:
    master_ip: "{{ hostvars[groups['masters'][0]].ansible_host}}"

- name: Print out master IP address
  debug: var=master_ip

- name: Generate kube token in master
  command: kubeadm token generate
  register: kube_token_output
  run_once: true

- name: Save kube token in master
  set_fact:
    kube_token: "{{ kube_token_output.stdout }}"

- name: Print out kube_token in master
  debug: var=kube_token

## kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.244.132
#- name: Reset Kubernetes cluster master component
#  shell: "kubeadm reset --force"
#  register: reset_cluster_master

#- name: Init Kubernetes cluster - master node
#  when: reset_cluster_master is succeeded
#  shell: |
#    kubeadm init --pod-network-cidr {{ pod_network_cidr }} \
#                 --token {{ token }} \
#                 --apiserver-advertise-address {{ master_ip }} \
#                 {{ kubeadm_opts }} \
#                 {{ init_opts }}
#  register: init_cluster
