---
# tasks file for master
- name: Get master node IP address
  set_fact:
    master_ip: "{{ hostvars[groups['masters'][0]].ansible_host}}"

- name: Print out master IP address
  debug: var=master_ip

#- name: Generate token from master
#  command: kubeadm token generate
#  register: kube_token
#  run_once: true

- name: Save kubeadm token in master
  set_fact:
    kube_token: `kubeadm token generate`.stdout

- name: Print out kube_token from master
  debug: var=kube_token

## kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.244.132
#- name: Reset Kubernetes cluster master component
#  shell: "kubeadm reset --force"
#  register: reset_cluster_master

#- name: Init Kubernetes cluster - master node
#  when: reset_cluster_master is succeeded
#  shell: |
#    kubeadm init --pod-network-cidr {{ pod_network_cidr }} \
#                 --token {{ token }} \
#                 --apiserver-advertise-address {{ master_ip }} \
#                 {{ kubeadm_opts }} \
#                 {{ init_opts }}
#  register: init_cluster