---
- debug:
    msg: "{{ansible_user}}"

- name: push ssh key                
  authorized_key:
    user: "{{ansible_user}}" 
    state: present
    key: "{{ lookup('file', '/home/{{ansible_user}}/.ssh/authorized_keys.pub') }}"
    manage_dir: yes 

#- name: test ping
#  ping:




